import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../lib/theme-provider";
import Link from "next/link";
import SignIn from "@/components/SignIn";
import { SignOut } from "@/components/SignOut";
import { JSX } from "react";
import ProfileNav from "@/components/ProfileNav";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem
        disableTransitionOnChange
      >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SessionProvider>
            <NavBar />
            {children}
          </SessionProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}

function NavBar() {
  return (
    <div className="bg-card flex place-content-center place-items-center outline px-8 relative">
      <div className="fixed start-8 justify-self-start shrink">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="#000000"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"></path>
          <path d="m3.3 7 8.7 5 8.7-5"></path>
          <path d="M12 22V12"></path>
        </svg>
      </div>
      <nav className="flex h-16 w-full flex-row place-content-evenly place-items-center xl:w-3/5">
        <NavLink link="/dashboard" content={<p>Dashboard</p>} />
        <NavLink
          link="/dashboard/collections/create"
          content={
            <svg
              className="stroke-foreground"
              xmlns="http://www.w3.org/2000/svg"
              width="36"
              height="36"
              viewBox="0 0 24 24"
              fill="none"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <rect
                strokeDasharray={3}
                width="18"
                height="18"
                x="3"
                y="3"
                rx="4"
              ></rect>
              <path d="M8 12h8"></path>
              <path d="M12 8v8"></path>
            </svg>
          }
        />
        <NavLink link="/dashboard/collections" content={<p>Collections</p>} />
      </nav>
      <div className="end-8 fixed justify-self-end">
        <ProfileNav />
      </div>
    </div>
  );
}

function NavLink({
  content,
  link,
  classname,
}: {
  content: JSX.Element;
  link: string;
  classname?: string;
}) {
  return (
    <Link className={classname} href={link}>
      {content}
    </Link>
  );
}
